#!/usr/bin/env python
"""
Generate configuration files from CSV tables and Cheetah templates.
"""
__author__ =  'Lorenz Schori'
__version__=  '0.1'

import sys
from Conficat.CLI import CLI

def main():
  ccat = CLI().parse(sys.argv)
  exit(ccat.run())

if __name__ == "__main__":
    main()
